version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    build:
      context: ./postgres
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
    env_file: ./postgres/.env
    ports:
      - "5432:5432"
    networks:
      - postgres_network
networks:
  postgres_network:
    driver: bridge
