# Generated by Django 5.0.6 on 2024-06-08 15:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Digest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "digest",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "db_table": "email",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("summary", models.TextField(default="")),
                ("published_at", models.DateTimeField()),
                ("source", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=255)),
                (
                    "vectorized_content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), default=list, size=None
                    ),
                ),
                ("lang", models.CharField(default="ru", max_length=2)),
                ("is_vectorized", models.BooleanField(default=False)),
                ("is_translated", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "news_news",
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("prompt", models.TextField()),
                ("in_use", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "prompt",
            },
        ),
    ]
