# Generated by Django 5.0.6 on 2024-06-08 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="vectorized_content",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(), default=list, null=True,
                size=None
            ),
        ),
        migrations.AlterModelTable(
            name="news",
            table="news",
        ),
        migrations.RunSQL(
            sql='ALTER TABLE news ALTER COLUMN summary SET DEFAULT \'\'',
            reverse_sql='ALTER TABLE news ALTER COLUMN summary DROP DEFAULT',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE news ALTER COLUMN is_translated SET DEFAULT FALSE',
            reverse_sql='ALTER TABLE news ALTER COLUMN is_translated DROP DEFAULT',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE news ALTER COLUMN is_vectorized SET DEFAULT FALSE',
            reverse_sql='ALTER TABLE news ALTER COLUMN is_vectorized DROP DEFAULT',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE news ALTER COLUMN is_public SET DEFAULT FALSE',
            reverse_sql='ALTER TABLE news ALTER COLUMN is_public DROP DEFAULT',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE news ALTER COLUMN content SET DEFAULT \'\'',
            reverse_sql='ALTER TABLE news ALTER COLUMN content DROP DEFAULT',
        )
    ]
