# Generated by Django 5.0.6 on 2024-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_news_is_requested_for_summarization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="vectorized_content",
            field=models.TextField(default=""),
        ),
        migrations.RunSQL(
            "UPDATE news SET vectorized_content = '' WHERE vectorized_content IS NULL"
        ),
    ]
